// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SegishopAPI.Data;

#nullable disable

namespace SegishopAPI.Migrations
{
    [DbContext(typeof(SegishopDbContext))]
    [Migration("20250823082504_AddShippingSystem")]
    partial class AddShippingSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SegishopAPI.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ProductAttributes")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId", "ProductId", "ProductAttributes")
                        .IsUnique()
                        .HasFilter("[ProductAttributes] IS NOT NULL");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("SegishopAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConfigurationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasFilter("[Slug] IS NOT NULL");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConfigurationType = "Regular",
                            CreatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 453, DateTimeKind.Utc).AddTicks(9940),
                            Description = "Electronic devices and gadgets",
                            IsActive = true,
                            Name = "Electronics",
                            Slug = "electronics",
                            SortOrder = 0,
                            UpdatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 453, DateTimeKind.Utc).AddTicks(9942)
                        },
                        new
                        {
                            Id = 2,
                            ConfigurationType = "Regular",
                            CreatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 453, DateTimeKind.Utc).AddTicks(9945),
                            Description = "Fashion and apparel",
                            IsActive = true,
                            Name = "Clothing",
                            Slug = "clothing",
                            SortOrder = 0,
                            UpdatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 453, DateTimeKind.Utc).AddTicks(9946)
                        },
                        new
                        {
                            Id = 3,
                            ConfigurationType = "Regular",
                            CreatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 453, DateTimeKind.Utc).AddTicks(9948),
                            Description = "Books and literature",
                            IsActive = true,
                            Name = "Books",
                            Slug = "books",
                            SortOrder = 0,
                            UpdatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 453, DateTimeKind.Utc).AddTicks(9949)
                        },
                        new
                        {
                            Id = 4,
                            ConfigurationType = "Regular",
                            CreatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 453, DateTimeKind.Utc).AddTicks(9951),
                            Description = "Home improvement and gardening",
                            IsActive = true,
                            Name = "Home & Garden",
                            Slug = "home-garden",
                            SortOrder = 0,
                            UpdatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 453, DateTimeKind.Utc).AddTicks(9951)
                        });
                });

            modelBuilder.Entity("SegishopAPI.Models.CategoryConfigurationTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ConfigurationTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("InheritToSubcategories")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ConfigurationTypeId");

                    b.HasIndex("CategoryId", "ConfigurationTypeId")
                        .IsUnique();

                    b.ToTable("CategoryConfigurationTemplates");
                });

            modelBuilder.Entity("SegishopAPI.Models.ConfigurationOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConfigurationTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("PriceModifier")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("PriceType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("fixed");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationTypeId");

                    b.HasIndex("ConfigurationTypeId", "SortOrder");

                    b.ToTable("ConfigurationOptions");
                });

            modelBuilder.Entity("SegishopAPI.Models.ConfigurationType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRequired")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("ShowPriceImpact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("Type", "IsActive");

                    b.ToTable("ConfigurationTypes");
                });

            modelBuilder.Entity("SegishopAPI.Models.FilterOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FilterType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("MaxValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId", "Name");

                    b.ToTable("FilterOptions");
                });

            modelBuilder.Entity("SegishopAPI.Models.FilterOptionValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("DisplayValue")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("FilterOptionId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("FilterOptionId", "Value");

                    b.ToTable("FilterOptionValues");
                });

            modelBuilder.Entity("SegishopAPI.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BillingAddress")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BillingCity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BillingCountry")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BillingName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BillingPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("BillingState")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("BillingZip")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("PaymentTransactionId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("ShippingAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ShippingCity")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingCountry")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingMethodTitle")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ShippingPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ShippingState")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ShippingZip")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("ShippingZoneMethodId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("ShippingZoneMethodId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("SegishopAPI.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<string>("ProductAttributes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProductSKU")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("SegishopAPI.Models.OrderItemConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ConfigurationOptionId")
                        .HasColumnType("int");

                    b.Property<int>("ConfigurationTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CustomValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationOptionId");

                    b.HasIndex("ConfigurationTypeId");

                    b.HasIndex("OrderItemId");

                    b.ToTable("OrderItemConfigurations");
                });

            modelBuilder.Entity("SegishopAPI.Models.PasswordResetToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsUsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Token");

                    b.HasIndex("UserId");

                    b.HasIndex("Token", "IsUsed", "ExpiresAt");

                    b.ToTable("PasswordResetTokens");
                });

            modelBuilder.Entity("SegishopAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Attributes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ImageGallery")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LongDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MetaDescription")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MetaTitle")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("SalePrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ShippingClassId")
                        .HasColumnType("int");

                    b.Property<string>("Slug")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Stock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SKU")
                        .IsUnique()
                        .HasFilter("[SKU] IS NOT NULL");

                    b.HasIndex("ShippingClassId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SegishopAPI.Models.ProductAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductAttributes");
                });

            modelBuilder.Entity("SegishopAPI.Models.ProductConfigurationOverride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConfigurationTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CustomOptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("OverrideType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("inherit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationTypeId");

                    b.HasIndex("ProductId");

                    b.HasIndex("ProductId", "ConfigurationTypeId")
                        .IsUnique();

                    b.ToTable("ProductConfigurationOverrides");
                });

            modelBuilder.Entity("SegishopAPI.Models.ProductFilterValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("CustomValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("FilterOptionId")
                        .HasColumnType("int");

                    b.Property<int?>("FilterOptionValueId")
                        .HasColumnType("int");

                    b.Property<decimal?>("NumericValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FilterOptionId");

                    b.HasIndex("FilterOptionValueId");

                    b.HasIndex("ProductId", "FilterOptionId");

                    b.ToTable("ProductFilterValues");
                });

            modelBuilder.Entity("SegishopAPI.Models.ProductHighlight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Highlight")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductHighlights");
                });

            modelBuilder.Entity("SegishopAPI.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");
                });

            modelBuilder.Entity("SegishopAPI.Models.ShippingClass", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("ShippingClasses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7161),
                            Description = "Standard shipping for Segi Bella products",
                            Name = "Segi Bella",
                            Slug = "segi-bella",
                            UpdatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7162)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7193),
                            Description = "Bulk snack orders requiring higher shipping costs",
                            Name = "Segi Snacks - Bulk",
                            Slug = "segi-snacks-bulk",
                            UpdatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7194)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7199),
                            Description = "Individual snack packs",
                            Name = "Segi Snacks - Individual",
                            Slug = "segi-snacks-individual",
                            UpdatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7200)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7203),
                            Description = "Wholesale invoice event orders",
                            Name = "Segi Snacks - Invoice_Event Wholesale",
                            Slug = "segi-snacks-invoice",
                            UpdatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7204)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7209),
                            Description = "Variety box configurations",
                            Name = "Segi Snacks - Variety Box",
                            Slug = "segi-snacks-variety-box",
                            UpdatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7210)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7213),
                            Description = "Wholesale snack orders",
                            Name = "Segi Snacks - Wholesale",
                            Slug = "segi-snacks-wholesale",
                            UpdatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7214)
                        });
                });

            modelBuilder.Entity("SegishopAPI.Models.ShippingClassCost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("CostType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Fixed");

                    b.Property<int>("ShippingClassId")
                        .HasColumnType("int");

                    b.Property<int>("ShippingZoneMethodId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShippingClassId");

                    b.HasIndex("ShippingZoneMethodId");

                    b.ToTable("ShippingClassCosts");
                });

            modelBuilder.Entity("SegishopAPI.Models.ShippingMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsTaxable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("MethodType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("ShippingMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7335),
                            Description = "Standard delivery service",
                            IsEnabled = true,
                            IsTaxable = true,
                            MethodType = "FlatRate",
                            Name = "Standard Shipping",
                            UpdatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7336)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7343),
                            Description = "Faster delivery service",
                            IsEnabled = true,
                            IsTaxable = true,
                            MethodType = "FlatRate",
                            Name = "Express Shipping",
                            UpdatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7344)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7348),
                            Description = "Next business day delivery",
                            IsEnabled = true,
                            IsTaxable = true,
                            MethodType = "FlatRate",
                            Name = "Next Day Air",
                            UpdatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7349)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7352),
                            Description = "Free shipping with conditions",
                            IsEnabled = true,
                            IsTaxable = false,
                            MethodType = "FreeShipping",
                            Name = "Free Standard Shipping",
                            UpdatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7353)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7356),
                            Description = "Customer pickup at store location",
                            IsEnabled = true,
                            IsTaxable = false,
                            MethodType = "LocalPickup",
                            Name = "Local Pickup",
                            UpdatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7357)
                        });
                });

            modelBuilder.Entity("SegishopAPI.Models.ShippingZone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.ToTable("ShippingZones");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7507),
                            Description = "Local delivery within 25 miles",
                            IsEnabled = true,
                            Name = "Local - 25miles",
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7508)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7518),
                            Description = "East coast states",
                            IsEnabled = true,
                            Name = "Zone 1 (East Coast and Nearby States)",
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7519)
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7523),
                            Description = "Central United States",
                            IsEnabled = true,
                            Name = "Zone 2 (Central U.S.)",
                            SortOrder = 3,
                            UpdatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7524)
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7528),
                            Description = "West coast and distant states",
                            IsEnabled = true,
                            Name = "Zone 3 (West Coast and Distant States)",
                            SortOrder = 4,
                            UpdatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7528)
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7537),
                            Description = "International shipping to North America",
                            IsEnabled = true,
                            Name = "International - North America / Caribbean",
                            SortOrder = 5,
                            UpdatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7538)
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7541),
                            Description = "International shipping to South America",
                            IsEnabled = true,
                            Name = "International - South America",
                            SortOrder = 6,
                            UpdatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7542)
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7545),
                            Description = "All other international destinations",
                            IsEnabled = true,
                            Name = "Rest of the world",
                            SortOrder = 7,
                            UpdatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(7546)
                        });
                });

            modelBuilder.Entity("SegishopAPI.Models.ShippingZoneMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseCost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int?>("EstimatedDaysMax")
                        .HasColumnType("int");

                    b.Property<int?>("EstimatedDaysMin")
                        .HasColumnType("int");

                    b.Property<bool>("IsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("MaxOrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinOrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("RequiresCoupon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int>("ShippingMethodId")
                        .HasColumnType("int");

                    b.Property<int>("ShippingZoneId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ShippingMethodId");

                    b.HasIndex("ShippingZoneId");

                    b.ToTable("ShippingZoneMethods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BaseCost = 5.99m,
                            EstimatedDaysMax = 10,
                            EstimatedDaysMin = 3,
                            IsEnabled = true,
                            MinOrderAmount = 75m,
                            RequiresCoupon = false,
                            ShippingMethodId = 1,
                            ShippingZoneId = 1,
                            SortOrder = 1,
                            Title = "Standard Shipping (3-10 business days)"
                        },
                        new
                        {
                            Id = 2,
                            BaseCost = 15.00m,
                            EstimatedDaysMax = 4,
                            EstimatedDaysMin = 1,
                            IsEnabled = true,
                            RequiresCoupon = false,
                            ShippingMethodId = 2,
                            ShippingZoneId = 1,
                            SortOrder = 2,
                            Title = "Express Shipping (1-4 Business Days)"
                        },
                        new
                        {
                            Id = 3,
                            BaseCost = 25.00m,
                            EstimatedDaysMax = 1,
                            EstimatedDaysMin = 1,
                            IsEnabled = true,
                            RequiresCoupon = false,
                            ShippingMethodId = 3,
                            ShippingZoneId = 1,
                            SortOrder = 3,
                            Title = "Next Day Air (1 Business Day)"
                        },
                        new
                        {
                            Id = 4,
                            BaseCost = 0m,
                            EstimatedDaysMax = 10,
                            EstimatedDaysMin = 3,
                            IsEnabled = true,
                            MinOrderAmount = 75m,
                            RequiresCoupon = false,
                            ShippingMethodId = 4,
                            ShippingZoneId = 1,
                            SortOrder = 4,
                            Title = "Free Standard Shipping (3-10 Business Days)"
                        },
                        new
                        {
                            Id = 5,
                            BaseCost = 0m,
                            EstimatedDaysMax = 0,
                            EstimatedDaysMin = 0,
                            IsEnabled = true,
                            RequiresCoupon = false,
                            ShippingMethodId = 5,
                            ShippingZoneId = 1,
                            SortOrder = 5,
                            Title = "Farmers Market Pickup: West End, Del Ray, Reston, or Crystal City"
                        },
                        new
                        {
                            Id = 6,
                            BaseCost = 8.99m,
                            EstimatedDaysMax = 10,
                            EstimatedDaysMin = 3,
                            IsEnabled = true,
                            MinOrderAmount = 75m,
                            RequiresCoupon = false,
                            ShippingMethodId = 1,
                            ShippingZoneId = 2,
                            SortOrder = 1,
                            Title = "Standard Shipping (3-10 business days)"
                        },
                        new
                        {
                            Id = 7,
                            BaseCost = 18.00m,
                            EstimatedDaysMax = 4,
                            EstimatedDaysMin = 1,
                            IsEnabled = true,
                            RequiresCoupon = false,
                            ShippingMethodId = 2,
                            ShippingZoneId = 2,
                            SortOrder = 2,
                            Title = "Express Shipping (1-4 Business Days)"
                        },
                        new
                        {
                            Id = 8,
                            BaseCost = 28.00m,
                            EstimatedDaysMax = 1,
                            EstimatedDaysMin = 1,
                            IsEnabled = true,
                            RequiresCoupon = false,
                            ShippingMethodId = 3,
                            ShippingZoneId = 2,
                            SortOrder = 3,
                            Title = "Next Day Air (1 Business Day)"
                        },
                        new
                        {
                            Id = 9,
                            BaseCost = 0m,
                            EstimatedDaysMax = 10,
                            EstimatedDaysMin = 3,
                            IsEnabled = true,
                            MinOrderAmount = 75m,
                            RequiresCoupon = false,
                            ShippingMethodId = 4,
                            ShippingZoneId = 2,
                            SortOrder = 4,
                            Title = "Free Standard Shipping (3-10 Business Days)"
                        },
                        new
                        {
                            Id = 10,
                            BaseCost = 12.99m,
                            EstimatedDaysMax = 10,
                            EstimatedDaysMin = 3,
                            IsEnabled = true,
                            MinOrderAmount = 75m,
                            RequiresCoupon = false,
                            ShippingMethodId = 1,
                            ShippingZoneId = 3,
                            SortOrder = 1,
                            Title = "Standard Shipping (3-10 business days)"
                        },
                        new
                        {
                            Id = 11,
                            BaseCost = 22.00m,
                            EstimatedDaysMax = 4,
                            EstimatedDaysMin = 1,
                            IsEnabled = true,
                            RequiresCoupon = false,
                            ShippingMethodId = 2,
                            ShippingZoneId = 3,
                            SortOrder = 2,
                            Title = "Express Shipping (1-4 Business Days)"
                        },
                        new
                        {
                            Id = 12,
                            BaseCost = 32.00m,
                            EstimatedDaysMax = 1,
                            EstimatedDaysMin = 1,
                            IsEnabled = true,
                            RequiresCoupon = false,
                            ShippingMethodId = 3,
                            ShippingZoneId = 3,
                            SortOrder = 3,
                            Title = "Next Day Air (1 Business Day)"
                        },
                        new
                        {
                            Id = 13,
                            BaseCost = 0m,
                            EstimatedDaysMax = 10,
                            EstimatedDaysMin = 3,
                            IsEnabled = true,
                            MinOrderAmount = 75m,
                            RequiresCoupon = false,
                            ShippingMethodId = 4,
                            ShippingZoneId = 3,
                            SortOrder = 4,
                            Title = "Free Standard Shipping (3-10 Business Days)"
                        },
                        new
                        {
                            Id = 14,
                            BaseCost = 19.99m,
                            EstimatedDaysMax = 20,
                            EstimatedDaysMin = 6,
                            IsEnabled = true,
                            RequiresCoupon = false,
                            ShippingMethodId = 1,
                            ShippingZoneId = 5,
                            SortOrder = 1,
                            Title = "International Flat Rate (6-20 Business Days)"
                        },
                        new
                        {
                            Id = 15,
                            BaseCost = 24.99m,
                            EstimatedDaysMax = 20,
                            EstimatedDaysMin = 6,
                            IsEnabled = true,
                            RequiresCoupon = false,
                            ShippingMethodId = 1,
                            ShippingZoneId = 6,
                            SortOrder = 1,
                            Title = "International Flat Rate (6-20 Business Days)"
                        },
                        new
                        {
                            Id = 16,
                            BaseCost = 29.99m,
                            EstimatedDaysMax = 20,
                            EstimatedDaysMin = 6,
                            IsEnabled = true,
                            RequiresCoupon = false,
                            ShippingMethodId = 1,
                            ShippingZoneId = 7,
                            SortOrder = 1,
                            Title = "International Flat Rate (6-20 Business Days)"
                        });
                });

            modelBuilder.Entity("SegishopAPI.Models.ShippingZoneRegion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsIncluded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RegionType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("ShippingZoneId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShippingZoneId");

                    b.ToTable("ShippingZoneRegions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsIncluded = true,
                            Priority = 1,
                            RegionCode = "MD",
                            RegionName = "Maryland",
                            RegionType = "State",
                            ShippingZoneId = 1
                        },
                        new
                        {
                            Id = 2,
                            IsIncluded = true,
                            Priority = 1,
                            RegionCode = "VA",
                            RegionName = "Virginia",
                            RegionType = "State",
                            ShippingZoneId = 1
                        },
                        new
                        {
                            Id = 3,
                            IsIncluded = true,
                            Priority = 1,
                            RegionCode = "DC",
                            RegionName = "District of Columbia",
                            RegionType = "State",
                            ShippingZoneId = 1
                        },
                        new
                        {
                            Id = 4,
                            IsIncluded = true,
                            Priority = 1,
                            RegionCode = "DE",
                            RegionName = "Delaware",
                            RegionType = "State",
                            ShippingZoneId = 2
                        },
                        new
                        {
                            Id = 5,
                            IsIncluded = true,
                            Priority = 1,
                            RegionCode = "NJ",
                            RegionName = "New Jersey",
                            RegionType = "State",
                            ShippingZoneId = 2
                        },
                        new
                        {
                            Id = 6,
                            IsIncluded = true,
                            Priority = 1,
                            RegionCode = "NY",
                            RegionName = "New York",
                            RegionType = "State",
                            ShippingZoneId = 2
                        },
                        new
                        {
                            Id = 7,
                            IsIncluded = true,
                            Priority = 1,
                            RegionCode = "PA",
                            RegionName = "Pennsylvania",
                            RegionType = "State",
                            ShippingZoneId = 2
                        },
                        new
                        {
                            Id = 8,
                            IsIncluded = true,
                            Priority = 1,
                            RegionCode = "NC",
                            RegionName = "North Carolina",
                            RegionType = "State",
                            ShippingZoneId = 2
                        },
                        new
                        {
                            Id = 9,
                            IsIncluded = true,
                            Priority = 1,
                            RegionCode = "SC",
                            RegionName = "South Carolina",
                            RegionType = "State",
                            ShippingZoneId = 2
                        },
                        new
                        {
                            Id = 10,
                            IsIncluded = true,
                            Priority = 1,
                            RegionCode = "WV",
                            RegionName = "West Virginia",
                            RegionType = "State",
                            ShippingZoneId = 2
                        },
                        new
                        {
                            Id = 11,
                            IsIncluded = true,
                            Priority = 1,
                            RegionCode = "AL",
                            RegionName = "Alabama",
                            RegionType = "State",
                            ShippingZoneId = 3
                        },
                        new
                        {
                            Id = 12,
                            IsIncluded = true,
                            Priority = 1,
                            RegionCode = "AR",
                            RegionName = "Arkansas",
                            RegionType = "State",
                            ShippingZoneId = 3
                        },
                        new
                        {
                            Id = 13,
                            IsIncluded = true,
                            Priority = 1,
                            RegionCode = "GA",
                            RegionName = "Georgia",
                            RegionType = "State",
                            ShippingZoneId = 3
                        },
                        new
                        {
                            Id = 14,
                            IsIncluded = true,
                            Priority = 1,
                            RegionCode = "IL",
                            RegionName = "Illinois",
                            RegionType = "State",
                            ShippingZoneId = 3
                        },
                        new
                        {
                            Id = 15,
                            IsIncluded = true,
                            Priority = 1,
                            RegionCode = "IN",
                            RegionName = "Indiana",
                            RegionType = "State",
                            ShippingZoneId = 3
                        },
                        new
                        {
                            Id = 16,
                            IsIncluded = true,
                            Priority = 1,
                            RegionCode = "IA",
                            RegionName = "Iowa",
                            RegionType = "State",
                            ShippingZoneId = 3
                        },
                        new
                        {
                            Id = 17,
                            IsIncluded = true,
                            Priority = 1,
                            RegionCode = "KY",
                            RegionName = "Kentucky",
                            RegionType = "State",
                            ShippingZoneId = 3
                        },
                        new
                        {
                            Id = 18,
                            IsIncluded = true,
                            Priority = 1,
                            RegionCode = "LA",
                            RegionName = "Louisiana",
                            RegionType = "State",
                            ShippingZoneId = 3
                        },
                        new
                        {
                            Id = 19,
                            IsIncluded = true,
                            Priority = 1,
                            RegionCode = "MI",
                            RegionName = "Michigan",
                            RegionType = "State",
                            ShippingZoneId = 3
                        },
                        new
                        {
                            Id = 20,
                            IsIncluded = true,
                            Priority = 1,
                            RegionCode = "MN",
                            RegionName = "Minnesota",
                            RegionType = "State",
                            ShippingZoneId = 3
                        },
                        new
                        {
                            Id = 21,
                            IsIncluded = true,
                            Priority = 1,
                            RegionCode = "CA",
                            RegionName = "Canada",
                            RegionType = "Country",
                            ShippingZoneId = 5
                        },
                        new
                        {
                            Id = 22,
                            IsIncluded = true,
                            Priority = 1,
                            RegionCode = "BR",
                            RegionName = "Brazil",
                            RegionType = "Country",
                            ShippingZoneId = 6
                        },
                        new
                        {
                            Id = 23,
                            IsIncluded = true,
                            Priority = 1,
                            RegionCode = "AR",
                            RegionName = "Argentina",
                            RegionType = "Country",
                            ShippingZoneId = 6
                        });
                });

            modelBuilder.Entity("SegishopAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Customer");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(5981),
                            Email = "admin@segishop.com",
                            FirstName = "Admin",
                            IsActive = true,
                            LastName = "User",
                            PasswordHash = "$2a$11$EBKUCl7ux5myZ/uS8T8dreEPa60UoQlCYyqa1qoDlI12/uRzH.4Pm",
                            Role = "Admin",
                            UpdatedAt = new DateTime(2025, 8, 23, 8, 25, 3, 601, DateTimeKind.Utc).AddTicks(5988)
                        });
                });

            modelBuilder.Entity("SegishopAPI.Models.CartItem", b =>
                {
                    b.HasOne("SegishopAPI.Models.Product", "Product")
                        .WithMany("CartItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SegishopAPI.Models.User", "User")
                        .WithMany("CartItems")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SegishopAPI.Models.Category", b =>
                {
                    b.HasOne("SegishopAPI.Models.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SegishopAPI.Models.CategoryConfigurationTemplate", b =>
                {
                    b.HasOne("SegishopAPI.Models.Category", "Category")
                        .WithMany("ConfigurationTemplates")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SegishopAPI.Models.ConfigurationType", "ConfigurationType")
                        .WithMany("CategoryTemplates")
                        .HasForeignKey("ConfigurationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("ConfigurationType");
                });

            modelBuilder.Entity("SegishopAPI.Models.ConfigurationOption", b =>
                {
                    b.HasOne("SegishopAPI.Models.ConfigurationType", "ConfigurationType")
                        .WithMany("Options")
                        .HasForeignKey("ConfigurationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigurationType");
                });

            modelBuilder.Entity("SegishopAPI.Models.FilterOption", b =>
                {
                    b.HasOne("SegishopAPI.Models.Category", "Category")
                        .WithMany("FilterOptions")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SegishopAPI.Models.FilterOptionValue", b =>
                {
                    b.HasOne("SegishopAPI.Models.FilterOption", "FilterOption")
                        .WithMany("FilterOptionValues")
                        .HasForeignKey("FilterOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilterOption");
                });

            modelBuilder.Entity("SegishopAPI.Models.Order", b =>
                {
                    b.HasOne("SegishopAPI.Models.ShippingZoneMethod", "ShippingZoneMethod")
                        .WithMany("Orders")
                        .HasForeignKey("ShippingZoneMethodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SegishopAPI.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ShippingZoneMethod");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SegishopAPI.Models.OrderItem", b =>
                {
                    b.HasOne("SegishopAPI.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SegishopAPI.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SegishopAPI.Models.OrderItemConfiguration", b =>
                {
                    b.HasOne("SegishopAPI.Models.ConfigurationOption", "ConfigurationOption")
                        .WithMany()
                        .HasForeignKey("ConfigurationOptionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SegishopAPI.Models.ConfigurationType", "ConfigurationType")
                        .WithMany()
                        .HasForeignKey("ConfigurationTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SegishopAPI.Models.OrderItem", "OrderItem")
                        .WithMany("Configurations")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigurationOption");

                    b.Navigation("ConfigurationType");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("SegishopAPI.Models.PasswordResetToken", b =>
                {
                    b.HasOne("SegishopAPI.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SegishopAPI.Models.Product", b =>
                {
                    b.HasOne("SegishopAPI.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SegishopAPI.Models.ShippingClass", "ShippingClass")
                        .WithMany("Products")
                        .HasForeignKey("ShippingClassId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Category");

                    b.Navigation("ShippingClass");
                });

            modelBuilder.Entity("SegishopAPI.Models.ProductAttribute", b =>
                {
                    b.HasOne("SegishopAPI.Models.Product", "Product")
                        .WithMany("ProductAttributes")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SegishopAPI.Models.ProductConfigurationOverride", b =>
                {
                    b.HasOne("SegishopAPI.Models.ConfigurationType", "ConfigurationType")
                        .WithMany("ProductOverrides")
                        .HasForeignKey("ConfigurationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SegishopAPI.Models.Product", "Product")
                        .WithMany("ConfigurationOverrides")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigurationType");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SegishopAPI.Models.ProductFilterValue", b =>
                {
                    b.HasOne("SegishopAPI.Models.FilterOption", "FilterOption")
                        .WithMany("ProductFilterValues")
                        .HasForeignKey("FilterOptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SegishopAPI.Models.FilterOptionValue", "FilterOptionValue")
                        .WithMany("ProductFilterValues")
                        .HasForeignKey("FilterOptionValueId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("SegishopAPI.Models.Product", "Product")
                        .WithMany("ProductFilterValues")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FilterOption");

                    b.Navigation("FilterOptionValue");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SegishopAPI.Models.ProductHighlight", b =>
                {
                    b.HasOne("SegishopAPI.Models.Product", "Product")
                        .WithMany("Highlights")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SegishopAPI.Models.ProductImage", b =>
                {
                    b.HasOne("SegishopAPI.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("SegishopAPI.Models.ShippingClassCost", b =>
                {
                    b.HasOne("SegishopAPI.Models.ShippingClass", "ShippingClass")
                        .WithMany("ClassCosts")
                        .HasForeignKey("ShippingClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SegishopAPI.Models.ShippingZoneMethod", "ShippingZoneMethod")
                        .WithMany("ClassCosts")
                        .HasForeignKey("ShippingZoneMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShippingClass");

                    b.Navigation("ShippingZoneMethod");
                });

            modelBuilder.Entity("SegishopAPI.Models.ShippingZoneMethod", b =>
                {
                    b.HasOne("SegishopAPI.Models.ShippingMethod", "ShippingMethod")
                        .WithMany("ZoneMethods")
                        .HasForeignKey("ShippingMethodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SegishopAPI.Models.ShippingZone", "ShippingZone")
                        .WithMany("Methods")
                        .HasForeignKey("ShippingZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShippingMethod");

                    b.Navigation("ShippingZone");
                });

            modelBuilder.Entity("SegishopAPI.Models.ShippingZoneRegion", b =>
                {
                    b.HasOne("SegishopAPI.Models.ShippingZone", "ShippingZone")
                        .WithMany("Regions")
                        .HasForeignKey("ShippingZoneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShippingZone");
                });

            modelBuilder.Entity("SegishopAPI.Models.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("ConfigurationTemplates");

                    b.Navigation("FilterOptions");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("SegishopAPI.Models.ConfigurationType", b =>
                {
                    b.Navigation("CategoryTemplates");

                    b.Navigation("Options");

                    b.Navigation("ProductOverrides");
                });

            modelBuilder.Entity("SegishopAPI.Models.FilterOption", b =>
                {
                    b.Navigation("FilterOptionValues");

                    b.Navigation("ProductFilterValues");
                });

            modelBuilder.Entity("SegishopAPI.Models.FilterOptionValue", b =>
                {
                    b.Navigation("ProductFilterValues");
                });

            modelBuilder.Entity("SegishopAPI.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SegishopAPI.Models.OrderItem", b =>
                {
                    b.Navigation("Configurations");
                });

            modelBuilder.Entity("SegishopAPI.Models.Product", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("ConfigurationOverrides");

                    b.Navigation("Highlights");

                    b.Navigation("Images");

                    b.Navigation("OrderItems");

                    b.Navigation("ProductAttributes");

                    b.Navigation("ProductFilterValues");
                });

            modelBuilder.Entity("SegishopAPI.Models.ShippingClass", b =>
                {
                    b.Navigation("ClassCosts");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("SegishopAPI.Models.ShippingMethod", b =>
                {
                    b.Navigation("ZoneMethods");
                });

            modelBuilder.Entity("SegishopAPI.Models.ShippingZone", b =>
                {
                    b.Navigation("Methods");

                    b.Navigation("Regions");
                });

            modelBuilder.Entity("SegishopAPI.Models.ShippingZoneMethod", b =>
                {
                    b.Navigation("ClassCosts");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("SegishopAPI.Models.User", b =>
                {
                    b.Navigation("CartItems");

                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
